name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: '3.12'

      - name: Install dependencies
        run: |
          uv pip install -e .[dev]

      - name: Run tests
        run: |
          uv run pytest -q

  smoke:
    name: smoke
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: '3.12'

      - name: Install runtime deps
        run: |
          uv pip install -e .

      - name: Check-only (fresnel)
        run: |
          uv run python src/pp_model.py --check-only --absorption-model fresnel

      - name: Check-only (kumar)
        run: |
          uv run python src/pp_model.py --check-only --absorption-model kumar

  docs:
    name: docs
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node for markdownlint
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install markdownlint-cli
        run: |
          npm install -g markdownlint-cli@0.41.x

      - name: Run markdownlint
        run: |
          markdownlint "**/*.md" --ignore node_modules --config .markdownlint.jsonc

      - name: Install Vale
        run: |
          curl -fsSL https://install.goreleaser.com/github.com/errata-ai/vale.sh | sh -s -- -b "$PWD/bin"

      - name: Run Vale
        run: |
          ./bin/vale --version
          ./bin/vale .
